### ISSUE TITLE
音頻編輯ui，文字轉語音時進行終止操作會發生崩潰

### ISSUE THREAD

**Issue by BiZhiChen01** [HMS-Core/hms-audio-editor-demo#13]
版本：com.huawei.hms:audio-editor-sdk:1.5.0.301

android.os.NetworkOnMainThreadException
        at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1605)
        at com.android.org.conscrypt.Platform.blockGuardOnNetwork(Platform.java:430)
        at com.android.org.conscrypt.ConscryptEngineSocket$SSLOutputStream.writeInternal(ConscryptEngineSocket.java:666)
        at com.android.org.conscrypt.ConscryptEngineSocket$SSLOutputStream.access$200(ConscryptEngineSocket.java:625)
        at com.android.org.conscrypt.ConscryptEngineSocket.drainOutgoingQueue(ConscryptEngineSocket.java:594)
        at com.android.org.conscrypt.ConscryptEngineSocket.close(ConscryptEngineSocket.java:489)
        at com.huawei.hms.network.embedded.u8.a(Unknown Source:2)
        at com.huawei.hms.network.embedded.o9.b(Unknown Source:66)
        at com.huawei.hms.network.embedded.p7.b(Unknown Source:2)
        at com.huawei.hms.network.embedded.b4.evictAll(Unknown Source:9)
        at com.huawei.hms.network.embedded.f.b(Unknown Source:4)
        at com.huawei.hms.network.embedded.h.evictAllConnections(Unknown Source:4)
        at com.huawei.hms.audioeditor.sdk.d.o.a(HttpUtils.java:46)
        at com.huawei.hms.audioeditor.sdk.d.q.b(SynthesisEngineOnline.java:6)
        at com.huawei.hms.audioeditor.sdk.d.i.f(SpeechSynthesisController.java:7)
        at com.huawei.hms.audioeditor.sdk.engine.dubbing.HAEAiDubbingEngine.shutdown(HAEAiDubbingEngine.java:2)
        at com.huawei.hms.audioeditor.ui.editor.panel.fragments.AudioTextToSpeechPanelFragment.i(AudioTextToSpeechPanelFragment.java:3)
        at com.huawei.hms.audioeditor.ui.editor.panel.fragments.AudioTextToSpeechPanelFragment.g(AudioTextToSpeechPanelFragment.java:2)
        at com.huawei.hms.audioeditor.ui.editor.panel.fragments.AudioTextToSpeechPanelFragment.$r8$lambda$NtAckNdVCHJwrJc9r6NxzdrduUo(Unknown Source:0)
        at com.huawei.hms.audioeditor.ui.editor.panel.fragments.AudioTextToSpeechPanelFragment$$ExternalSyntheticLambda3.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:8160)
        at android.view.View.performClickInternal(View.java:8137)
        at android.view.View.access$3700(View.java:888)
        at android.view.View$PerformClick.run(View.java:30236)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8633)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by Xuejiao-Shi** [comment]
开发者你好，感谢您提供此次报障线索，我们已经复现这个问题，预计将会在后续的版本中修复此问题，感谢您的支持和理解。

**Comment by Xuejiao-Shi** [comment]
您好，此问题已在新版本1.6.0.301中修复，请您验收一下。

**Comment by BiZhiChen01** [comment]
好的，感谢您的回复
