### ISSUE TITLE
Couldn't find "libHuaweiAudioEditCreativity.so" error.

### ISSUE THREAD

**Issue by CodingLoverPro** [HMS-Core/hms-audio-editor-demo#15]
Can't launch the app on Android 8, Android 11 (tested devices) using `com.huawei.hms:audio-editor-ui` SDK. The application did not launch on the device. It completely crashed when starting the app.

`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.huawei.hms.audioeditor.demo, PID: 8028
    java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.startup.StartupException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.huawei.hms.audioeditor.demo-ljcsFwEPmEsgSo7pebXtZQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.huawei.hms.audioeditor.demo-ljcsFwEPmEsgSo7pebXtZQ==/lib/x86_64, /system/lib64, /vendor/lib64]]] couldn't find "libHuaweiAudioEditCreativity.so"
        at android.app.ActivityThread.installProvider(ActivityThread.java:6288)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5851)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5772)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: androidx.startup.StartupException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.huawei.hms.audioeditor.demo-ljcsFwEPmEsgSo7pebXtZQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.huawei.hms.audioeditor.demo-ljcsFwEPmEsgSo7pebXtZQ==/lib/x86_64, /system/lib64, /vendor/lib64]]] couldn't find "libHuaweiAudioEditCreativity.so"
        at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:162)
        at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:198)
        at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:42)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1919)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1894)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6285)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5851) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5772) 
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
     Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.huawei.hms.audioeditor.demo-ljcsFwEPmEsgSo7pebXtZQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.huawei.hms.audioeditor.demo-ljcsFwEPmEsgSo7pebXtZQ==/lib/x86_64, /system/lib64, /vendor/lib64]]] couldn't find "libHuaweiAudioEditCreativity.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
        at java.lang.System.loadLibrary(System.java:1657)
        at com.huawei.hms.audioeditor.HAEEditorLibraryApplication.create(HAEEditorLibraryApplication.java:7)
        at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:155)
        at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:198) 
        at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:42) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1919) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1894) 
        at android.app.ActivityThread.installProvider(ActivityThread.java:6285) 
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5851) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5772) 
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) `

**Comment by Xuejiao-Shi** [comment]
Could you kindly help us with some information to locate this issue? 
1.The device model and OS version on which this issue happened.
2.What modifications have you made to the demo? and what was your integrated SDK and SDK version number?

**Comment by Juanjo3299** [comment]
This problem arose for me when I ran the application on virtual devices, since the SDK only has ABIS for arm64-v8a and armeabi-v7a and those devices in Windows by default are x86 or x86_64 and it does not run correctly on any of them.

**Comment by Juanjo3299** [comment]
Show your project settings, app/build.gradle, root/build.gradle and if you are using gradle > 7.1 show settings.gradle

**Comment by Xuejiao-Shi** [comment]
It is suspected that when the Gradle version is 7.0 or later, the .so library file is not packed when the phone is connected to run the project.
Run the following command to query the CPU ABI of your phone when the phone is connected:
` adb shell getprop ro.product.cpu.abi`
If the value is not armeabi-v7a or arm64-v8a, perform the following operations:
1. Add abiFilters to the build.gradle file at the application level.
```
android {
    defaultConfig {
		......
        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a"
        }
    }
}
```
2. Choose Build > Clean Project and clear the build files in the project.
![image](https://user-images.githubusercontent.com/99166105/179128199-ae2b63f7-b9d2-4c21-8e25-72d14bcdf278.png)


3. Rerun the project.

If the problem persists, it is recommended that you use the gradle version in the sample code first.

**Comment by CodingLoverPro** [comment]
Yeah, it's working with using abiFilters . But unable to run the app on emulators which are based on Android 9, 8, and 7. 
@Xuejiao-Shi @Juanjo3299 However, I sincerely appreciate your assistance, consideration, and time. Thanks.
