### ISSUE TITLE
音频编辑分割音频会奔溃

### ISSUE THREAD

**Issue by sss5982** [HMS-Core/hms-audio-editor-demo#7]
02-21 10:50:01.799 14073-14318/com.huawei.hms.audioeditor.demo E/OMXMaster: A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.
02-21 10:50:01.799 14073-14318/com.huawei.hms.audioeditor.demo E/ACodec: onConfigureComponent mime.c_str() = audio/raw
02-21 10:50:01.799 14073-14321/com.huawei.hms.audioeditor.demo E/OMXMaster: A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.
02-21 10:50:01.809 14073-14321/com.huawei.hms.audioeditor.demo E/ACodec: onConfigureComponent mime.c_str() = audio/raw
02-21 10:50:01.919 14073-14073/com.huawei.hms.audioeditor.demo E/art: dlopen("/data/app/com.huawei.hms.audioeditor.demo-1/lib/arm/libMediaSwsJni.so", RTLD_LAZY) failed: dlopen failed: empty/missing DT_HASH in "libimedia_histen_6_0.so" (built with --hash-style=gnu?)
02-21 10:50:01.919 14073-14073/com.huawei.hms.audioeditor.demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.huawei.hms.audioeditor.demo, PID: 14073
    java.lang.UnsatisfiedLinkError: dlopen failed: empty/missing DT_HASH in "libimedia_histen_6_0.so" (built with --hash-style=gnu?)
        at java.lang.Runtime.loadLibrary(Runtime.java:371)
        at java.lang.System.loadLibrary(System.java:988)
        at com.huawei.hms.audioeditor.sdk.engine.audio.SoundGround.<clinit>(SoundGround.java:1)
        at com.huawei.hms.audioeditor.sdk.engine.audio.b.a(AudioEngine.java:47)
        at com.huawei.hms.audioeditor.sdk.asset.HAEAudioAsset.setRequestParas(HAEAudioAsset.java:1)
        at com.huawei.hms.audioeditor.sdk.asset.HAEAudioAsset.copy(HAEAudioAsset.java:12)
        at com.huawei.hms.audioeditor.sdk.lane.HAEAudioLane.a(HAEAudioLane.java:40)
        at com.huawei.hms.audioeditor.sdk.p.Gc.b(SplitActionAtAudioLane.java:3)
        at com.huawei.hms.audioeditor.sdk.history.a.a(Action.java:1)
        at com.huawei.hms.audioeditor.sdk.lane.HAEAudioLane.splitAsset(HAEAudioLane.java:5)
        at com.huawei.hms.audioeditor.ui.editor.menu.b.c(AudioEditMenuViewModel.java:9)
        at com.huawei.hms.audioeditor.ui.editor.menu.AudioEditMenuFragment.a(AudioEditMenuFragment.java:38)
        at com.huawei.hms.audioeditor.ui.editor.menu.AudioEditMenuAdapter$AudioEditMenuViewHolder.a(AudioEditMenuAdapter.java:5)
        at com.huawei.hms.audioeditor.ui.editor.menu.AudioEditMenuAdapter$AudioEditMenuViewHolder.lambda$VKdrIwns3htTY4DAhJnNmey0eHg(AudioEditMenuAdapter.java)
        at com.huawei.hms.audioeditor.ui.editor.menu.-$$Lambda$AudioEditMenuAdapter$AudioEditMenuViewHolder$VKdrIwns3htTY4DAhJnNmey0eHg.onClick(lambda)
        at android.view.View.performClick(View.java:5246)
        at android.widget.TextView.performClick(TextView.java:10626)
        at android.view.View$PerformClick.run(View.java:21256)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:145)
        at android.app.ActivityThread.main(ActivityThread.java:6959)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

**Comment by sss5982** [comment]
Android 5 会崩溃，底部菜单上的功能选择使用后也会出现一样的问题

**Comment by coolleizhu** [comment]
Which phone you used to test? What is the exact phone model and OS version?

**Comment by sss5982** [comment]
> 你用过什么手机测试过的手机型号和操作系统版本是什么？

Phone: GALAXY J3 Pro (SM-J3110)
Version: Android 5.1.1

**Comment by coolleizhu** [comment]
请问下您使用的AudioEditor是哪个版本的，另外系统里安装的HMS Core是哪个版本的？

**Comment by sss5982** [comment]
都是目前最新的版本

**Comment by coolleizhu** [comment]
你试着用Release编译后的APK，可能会解决

**Comment by coolleizhu** [comment]
@sss5982 请问这个问题现在解决了吗？在CSDN中看到这样的说明，看起来和你描述的情况比较类似，可以参考：
https://blog.csdn.net/weixin_44053702/article/details/113645461
